### ISSUE TITLE
Sending login information using query string...

### ISSUE THREAD

**Issue by WindzCUHK** [ierg4210/shop41#1]
![screen shot 2015-05-06 at 10 04 00 pm](https://cloud.githubusercontent.com/assets/6819063/7498843/56256fa2-f456-11e4-9e8d-6f43f58a1068.png)
![screen shot 2015-05-06 at 10 04 10 pm](https://cloud.githubusercontent.com/assets/6819063/7498844/5648cf1a-f456-11e4-8d50-9a79af31c58d.png)

Don't know is this it a valid issue but may cause information leak.

Details steps:
1. go to https://store41.ierg4210.org/account, should redirect to login page
2. use inspect element to get the _csrf value in the login form
3. copy the _csrf value
4. go to http://appsrv.cse.cuhk.edu.hk/~wkfan2/ierg4210/store41-loginPOST.html
5. paste the _csrf value to craft a HTTP (not HTTPS) POST request without body which still can login
6. go to https://store41.ierg4210.org/account, should be login success

Problems:
although HTTPS also encrypt the URL, username and password may still exist in some of the server log (not sure).
If HTTP is used in login POST, personal credential will definitely be leaked in the server access log.

Fix:
put the query string parameters in post body

![screen shot 2015-05-06 at 10 04 10 pm](https://cloud.githubusercontent.com/assets/6819063/7498854/67e5bc38-f456-11e4-963f-54589bd48a76.png)
![screen shot 2015-05-06 at 10 04 00 pm](https://cloud.githubusercontent.com/assets/6819063/7498853/67ac8580-f456-11e4-8c15-97a8a0bed3b8.png)

**Comment by s1155043799** [comment]
Hi, thank you for this trying.

It may not be neat by putting email and password directly in the URL string; yet, for laziness and for HTTPS encryption, I didn't bother to do it fancier.

For your other concerns,
1.  Username and password does not exist in any of the server log.
2.  HTTP should not be used in login POST. That's why we are required to enforce HTTPS in log-in pages for URL encryption. 
3.  If you do not know any user account and password before hand, (Like the way I release the entire admin and guest credentials already), you will not be able to log in by only knowing the _CSRF value. So what you have done is basically re-formatting the log-in page and sending the username and password in your own crafted page with the client-side _CSRF value.

Try harder!

**Comment by WindzCUHK** [comment]
Open /var/log/nginx/access.log

you should see a line
"POST https://store41.ierg4210.org/login/api/?username=admin@gmail.com&password=Hi1234&_csrf=4WGbrf3m-ygmNDuuIXIn1TMlzJlNsNkE1Bf0 HTTP/1.1"

**Comment by WindzCUHK** [comment]
testing

**Comment by WindzCUHK** [comment]
Go visit /var/log/nginx/access.log:

You should see a line even you request with HTTPS
"POST /login/api/?username=admin@gmail.com&password=Hi1234&_csrf=KfnVIVyP-lgipfc6-CIk2G9zreEbC-NZTd4s HTTP/1.1"
inside you EC2

and the file is unencrypted or salted
